# Site Configs
name: 金矢科技
description: 
url: http://arrking.com
markdown: redcarpet
highlighter: pygments
permalink: /blog/:title
paginate: 5
paginate_path: "blog/page:num"

# Default news if the page didnt enter news
news: 我们的DevOps团队，可以满足不同行业的客户，用扎实的技术基础，一流的服务精神，用心帮助您解决问题。
exclude: [node_modules, scss]

# Latest Version Config
latest_download: http://code.ionicframework.com/1.0.0-beta.13/ionic-v1.0.0-beta.13.zip
latest_version: 1.0.0-beta.13 "lanthanum-leopard"
latest_release_date: 2014-09-24

# Which version of AngularJS the latest build includes
included_angular_version: 1.2.12

# Which active Cordova version we recommend
recommended_cordova_version: 3.3.1

# the primary plunkr to fork
code_sample_base_url: http://plnkr.co/edit/vD0O9M?p=preview
